services:
  db:
    image: postgres:15
    container_name: bookshop_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookshop_user -d bookshop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./book-shop
    container_name: bookshop_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
